# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.22.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/taoranxue/works/space

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/taoranxue/works/space

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/taoranxue/works/space/CMakeFiles /Users/taoranxue/works/space//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/taoranxue/works/space/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named space

# Build rule for target.
space: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 space
.PHONY : space

# fast build rule for target.
space/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/build
.PHONY : space/fast

camera.o: camera.cc.o
.PHONY : camera.o

# target to build an object file
camera.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/camera.cc.o
.PHONY : camera.cc.o

camera.i: camera.cc.i
.PHONY : camera.i

# target to preprocess a source file
camera.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/camera.cc.i
.PHONY : camera.cc.i

camera.s: camera.cc.s
.PHONY : camera.s

# target to generate assembly for a file
camera.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/camera.cc.s
.PHONY : camera.cc.s

error.o: error.cc.o
.PHONY : error.o

# target to build an object file
error.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/error.cc.o
.PHONY : error.cc.o

error.i: error.cc.i
.PHONY : error.i

# target to preprocess a source file
error.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/error.cc.i
.PHONY : error.cc.i

error.s: error.cc.s
.PHONY : error.s

# target to generate assembly for a file
error.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/error.cc.s
.PHONY : error.cc.s

glad.o: glad.cc.o
.PHONY : glad.o

# target to build an object file
glad.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/glad.cc.o
.PHONY : glad.cc.o

glad.i: glad.cc.i
.PHONY : glad.i

# target to preprocess a source file
glad.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/glad.cc.i
.PHONY : glad.cc.i

glad.s: glad.cc.s
.PHONY : glad.s

# target to generate assembly for a file
glad.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/glad.cc.s
.PHONY : glad.cc.s

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/main.cc.s
.PHONY : main.cc.s

mesh.o: mesh.cc.o
.PHONY : mesh.o

# target to build an object file
mesh.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/mesh.cc.o
.PHONY : mesh.cc.o

mesh.i: mesh.cc.i
.PHONY : mesh.i

# target to preprocess a source file
mesh.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/mesh.cc.i
.PHONY : mesh.cc.i

mesh.s: mesh.cc.s
.PHONY : mesh.s

# target to generate assembly for a file
mesh.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/mesh.cc.s
.PHONY : mesh.cc.s

model.o: model.cc.o
.PHONY : model.o

# target to build an object file
model.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/model.cc.o
.PHONY : model.cc.o

model.i: model.cc.i
.PHONY : model.i

# target to preprocess a source file
model.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/model.cc.i
.PHONY : model.cc.i

model.s: model.cc.s
.PHONY : model.s

# target to generate assembly for a file
model.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/model.cc.s
.PHONY : model.cc.s

shader.o: shader.cc.o
.PHONY : shader.o

# target to build an object file
shader.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/shader.cc.o
.PHONY : shader.cc.o

shader.i: shader.cc.i
.PHONY : shader.i

# target to preprocess a source file
shader.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/shader.cc.i
.PHONY : shader.cc.i

shader.s: shader.cc.s
.PHONY : shader.s

# target to generate assembly for a file
shader.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/shader.cc.s
.PHONY : shader.cc.s

stab_image.o: stab_image.cc.o
.PHONY : stab_image.o

# target to build an object file
stab_image.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/stab_image.cc.o
.PHONY : stab_image.cc.o

stab_image.i: stab_image.cc.i
.PHONY : stab_image.i

# target to preprocess a source file
stab_image.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/stab_image.cc.i
.PHONY : stab_image.cc.i

stab_image.s: stab_image.cc.s
.PHONY : stab_image.s

# target to generate assembly for a file
stab_image.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/stab_image.cc.s
.PHONY : stab_image.cc.s

strings.o: strings.cc.o
.PHONY : strings.o

# target to build an object file
strings.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/strings.cc.o
.PHONY : strings.cc.o

strings.i: strings.cc.i
.PHONY : strings.i

# target to preprocess a source file
strings.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/strings.cc.i
.PHONY : strings.cc.i

strings.s: strings.cc.s
.PHONY : strings.s

# target to generate assembly for a file
strings.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/strings.cc.s
.PHONY : strings.cc.s

texture.o: texture.cc.o
.PHONY : texture.o

# target to build an object file
texture.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/texture.cc.o
.PHONY : texture.cc.o

texture.i: texture.cc.i
.PHONY : texture.i

# target to preprocess a source file
texture.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/texture.cc.i
.PHONY : texture.cc.i

texture.s: texture.cc.s
.PHONY : texture.s

# target to generate assembly for a file
texture.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space.dir/build.make CMakeFiles/space.dir/texture.cc.s
.PHONY : texture.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... space"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... error.o"
	@echo "... error.i"
	@echo "... error.s"
	@echo "... glad.o"
	@echo "... glad.i"
	@echo "... glad.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mesh.o"
	@echo "... mesh.i"
	@echo "... mesh.s"
	@echo "... model.o"
	@echo "... model.i"
	@echo "... model.s"
	@echo "... shader.o"
	@echo "... shader.i"
	@echo "... shader.s"
	@echo "... stab_image.o"
	@echo "... stab_image.i"
	@echo "... stab_image.s"
	@echo "... strings.o"
	@echo "... strings.i"
	@echo "... strings.s"
	@echo "... texture.o"
	@echo "... texture.i"
	@echo "... texture.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

